app1/urls.py
from app1.views import *
from django.urls import path
app_name='app1'

urlpatterns=[
    path('dhoni/',dhoni,name='dhoni'),
]

app2/urls.py
from app2.views import *
from django.urls import path

app_name='app2'
urlpatterns=[
    path('rohit/',rohit,name='rohit'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app2
from app1.views import * 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dhoni/',dhoni,name='dhoni'),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def dhoni(request):
    return render(request,'dhoni.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def rohit(request):
    return render(request,'rohit.html')

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>dhoni page</h1>
        <h1>We are using Generic url mapping to get this page</h1>
        <a href="{% url 'app2:rohit' %}">go to rohit page</a>
    </center>
    
</body>
</html>

templates/rohit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Welcome to rohit page</h1>
        <h1>This is rendered by specific url mapping</h1>
        <a href="{% url 'dhoni' %}">Navigate to dhoni</a>
    </center>
    
</body>
</html>